layout_spectrum: 0.6661046
favicon: null
name: New England News Journal
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.7225969
  lightness: 0.227656
  saturation: 0.4241147
  rhythmicContrast: 0.3128162
  brandColors:
    - '#060606'
    - '#30384B'
    - '#912226'
    - '#918986'
    - '#E9AC9A'
typography_spectrum: 0.7478921
