name: New England News Journal
favicon: null
layout_spectrum: 0.6661046
typography_spectrum: 0.7478921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1715'
    - '#908066'
    - '#5B4D39'
    - '#D0BC9B'
    - '#FBF1D7'
  brandStrength: 0.7225969
  lightness: 0.227656
  saturation: 0.4241147
  rhythmicContrast: 0.3128162
purpose: []
