color:
  brandStrength: 0.7225969
  saturation: 0.4241147
  brandColors:
    - '#060606'
    - '#30384B'
    - '#912226'
    - '#918986'
    - '#E9AC9A'
  lightness: 0.227656
  rhythmicContrast: 0.3128162
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.6661046
purpose: []
name: New England News Journal
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7478921
